# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b334f4348f1bdf450c72611b1622a9d13b7e06d825fa6464ed56702f5aaf434b982a8be1bd08a56d3e680d4acd64c86a3575dc419f9aad7e5a9452502aa623a7

test:
  secret_key_base: 37e0e3e7e480ed53d8bdc8b1a111e50376c924a220abbbcfea1faa676c3849b273f25eff8ad7b20de8a8149136ced70c21af64a88edefa1a5b28df7e20a1036f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
